# Generated by Django 3.1.7 on 2021-03-25 09:40

from django.db import migrations, models
import hextech_core.core.utils.id


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210319_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=hextech_core.core.utils.id.RandomID('users.User'), primary_key=True, serialize=False, verbose_name='Random id'),
        ),
    ]
