# Generated by Django 3.1.7 on 2021-03-20 16:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210319_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
